---
# install needed python for ansible, otherwise ansible is not able to get facts and run the modules.
# python-passlib = htaccess module for password generation
# python-mysqldb = used for creating maysql db and users via mysql_db und mysql_user
# python-apt = used by apt module to install packages via apt
- name: bootstrap maschines
  hosts: icinga_maschines
  gather_facts: no
  remote_user: badmin
  become: yes
  become_method: sudo 
  pre_tasks:
    - raw: sudo apt-get -y install python python2.7 python-mysqldb python-passlib python-apt
      args:
        executable: /bin/sh
  tags:
    - bootstrap

- name: deploy icinga2 maschines with default configurations
  gather_facts: yes
  hosts: icinga_maschines
  remote_user: badmin
  become: yes
  become_method: sudo

  roles:
    - common
    # role webserver is executed by the dependency via roles/project-icinga/meta/main.yml
    - ssh-keys
    - project-icinga
