alias l='ls -la'
alias ll='ls -a'
alias ..='cd ..'
alias ...='cd ../../'
alias showinetsockets='netstat -panA inet -A inet6 |grep LISTEN'
alias showinetsockets2='lsof -i -n |grep LISTEN'
alias psg='ps -ef |grep '
alias p='ping'
