---
- name: check if git is installed
  apt: pkg=git state=latest

- name: install etckeeper
  apt: pkg=etckeeper state=latest

- name: deploy etckeeper config
  copy: src=etckeeper.conf dest=/etc/etckeeper/etckeeper.conf

- name: make an initial commit
  command: /usr/bin/etckeeper init ; /usr/bin/etckeeper commit "Initial commit" 
  args:
    creates: /etc/.git/index 
    chdir: /etc/
  
