---
- name: make ipv6 diable permanent
  copy: src=10-ipv6-disable.conf dest=/etc/sysctl.d/10-ipv6-disable.conf owner=root group=root mode=644

- name: delete net.ipv6.conf.all.disable_ipv6 entry in main sysctl.conf
  lineinfile: dest=/etc/sysctl.conf state=absent regexp="^net.ipv6.conf.all.disable_ipv6"

- name: delete net.ipv6.conf.default.disable_ipv6 entry in main sysctl.conf
  lineinfile: dest=/etc/sysctl.conf state=absent regexp="^net.ipv6.conf.default.disable_ipv6"

- name: delete net.ipv6.conf.lo.disable_ipv6 entry in main sysctl.conf
  lineinfile: dest=/etc/sysctl.conf state=absent regexp="^net.ipv6.conf.lo.disable_ipv6"
